# Demo: Tensor vs Parameter

In [1]:
import torch
import torch.nn as nn

### Make linear module

In [5]:
mod = nn.Linear(2,2, bias = False)

In [6]:
print(mod.weight)

Parameter containing:
tensor([[-0.1409,  0.2378],
        [ 0.2101, -0.2798]], requires_grad=True)


### Set the weights to be the identity matrix $W= \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

In [8]:
mod.weight[0,0]=1
mod.weight[0,1]=0
mod.weight[1,0]=0
mod.weight[1,1]=1

In [9]:
print(mod.weight)

Parameter containing:
tensor([[1., 0.],
        [0., 1.]], grad_fn=<CopySlices>)


### Let's try to do this better

In [10]:
mod = nn.Linear(2,2, bias = False)

In [13]:
print(mod.weight)

Parameter containing:
tensor([[ 0.0580,  0.2016],
        [-0.3642,  0.4796]], requires_grad=True)


### Create a weight matrix

In [14]:
W=torch.Tensor([[1,0],[0,1]])
print(W)

tensor([[1., 0.],
        [0., 1.]])


### Set the weight of the module to be equal to the weight matrix

In [15]:
mod.weight = W

TypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)

In [19]:
print(mod.weight)

Parameter containing:
tensor([[ 0.0580,  0.2016],
        [-0.3642,  0.4796]], requires_grad=True)


In [20]:
print(W)

tensor([[1., 0.],
        [0., 1.]])


In [21]:
W2= nn.Parameter(W)
print(W2)

Parameter containing:
tensor([[1., 0.],
        [0., 1.]], requires_grad=True)


### Now we can set the parameters of the module to be equal to the desired parameters

In [22]:
mod.weight = W2

In [23]:
print(mod.weight)

Parameter containing:
tensor([[1., 0.],
        [0., 1.]], requires_grad=True)


### Try the module with random input

In [29]:
x = torch.Tensor([5,13])
print(x)

tensor([ 5., 13.])


In [30]:
y = mod(x.view(1,2))
print(y)

tensor([[ 5., 13.]], grad_fn=<MmBackward>)
