# Demo torch.stack()

In [3]:
import torch

### Suppose I want to make an image with 3 channels:
$$
\text{channel 1 }=\begin{bmatrix}
1 & 1 \\
1 & 1
\end{bmatrix}
\qquad 
\text{channel 2 }=\begin{bmatrix}
0 & 0 \\
1 & 1
\end{bmatrix}
\qquad 
\text{channel 3 }=\begin{bmatrix}
1 & 1 \\
0 & 0
\end{bmatrix}
$$

In [4]:
ch1 = torch.Tensor([[1,1],[1,1]]) 
ch2 = torch.Tensor([[0,0],[1,1]]) 
ch3 = torch.Tensor([[1,1],[0,0]]) 

In [8]:
print(ch1)

tensor([[1., 1.],
        [1., 1.]])


In [9]:
print(ch2)

tensor([[0., 0.],
        [1., 1.]])


In [10]:
print(ch3)

tensor([[1., 1.],
        [0., 0.]])


### Now we can stack them into a 3-dimensional tensor as follow

In [16]:
image = torch.stack( [ch1,ch2,ch3] , dim=0 ) 

In [17]:
image

tensor([[[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [1., 1.]],

        [[1., 1.],
         [0., 0.]]])

### Another example

In [18]:
x=torch.Tensor([1,1,1,1,1])
y=torch.Tensor([2,2,2,2,2])

In [19]:
print(x)

tensor([1., 1., 1., 1., 1.])


In [20]:
print(y)

tensor([2., 2., 2., 2., 2.])


In [21]:
A=torch.stack([x,y], dim=0)

In [22]:
print(A)

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]])


In [23]:
B=torch.stack([x,y], dim=1)

In [24]:
print(B)

tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])
