# Problem 2 

###  Redo problem 1  but this time use Pytorch. You need to create a convolutional module with the desired weights. Set the bias to False. Then create the input image, feed it to the convolutional module and check that you obtain the same result than the one you computed by hand in the previous problem. 


* Hint 1: Use the command torch.stack() in order to build the input image and the filters. 
* Hint 2: You will need the command nn.Parameter() in order to convert tensors to parameters. 
* Hint 3: Don't forget that Pytorch only work with batch. So here you are going to do a batch of 1 image. Use the command view() in order to deal with this. 


In [1]:
import torch
import torch.nn as nn

conv = nn.Conv2d(2, 2, kernel_size = 2, bias = False)

In [2]:
im_ch1 = torch.Tensor([[4,3,2,1],[3,2,1,2],[2,1,2,3],[1,2,3,4]])
im_ch2 = torch.Tensor([[1,2,3,4],[2,1,2,3],[3,2,1,2],[1,3,2,1]])
im = torch.stack([im_ch1, im_ch2], dim = 0)
print(im)

fil1_ch1 = torch.Tensor([[0,1],[1,0]])
fil1_ch2 = torch.Tensor([[1,0],[0,1]])
fil1 = torch.stack([fil1_ch1, fil1_ch2], dim = 0)

fil2_ch1 = torch.Tensor([[0,1],[-1,0]])
fil2_ch2 = torch.Tensor([[2,0],[0,-1]])
fil2 = torch.stack([fil2_ch1, fil2_ch2])

fil = torch.stack([fil1, fil2], dim = 0)
p_fil = nn.Parameter(fil)
print(p_fil)

tensor([[[4., 3., 2., 1.],
         [3., 2., 1., 2.],
         [2., 1., 2., 3.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [2., 1., 2., 3.],
         [3., 2., 1., 2.],
         [1., 3., 2., 1.]]])
Parameter containing:
tensor([[[[ 0.,  1.],
          [ 1.,  0.]],

         [[ 1.,  0.],
          [ 0.,  1.]]],


        [[[ 0.,  1.],
          [-1.,  0.]],

         [[ 2.,  0.],
          [ 0., -1.]]]], requires_grad=True)


In [3]:
print(conv.weight)
conv.weight = p_fil
print(conv.weight)
mod = conv(im.view(1,2,4,4))

Parameter containing:
tensor([[[[ 0.3508,  0.2979],
          [ 0.1527,  0.1362]],

         [[ 0.1233, -0.1369],
          [-0.1777,  0.2799]]],


        [[[-0.1040,  0.0814],
          [ 0.2097,  0.2050]],

         [[ 0.2400,  0.2111],
          [ 0.0511, -0.1924]]]], requires_grad=True)
Parameter containing:
tensor([[[[ 0.,  1.],
          [ 1.,  0.]],

         [[ 1.,  0.],
          [ 0.,  1.]]],


        [[[ 0.,  1.],
          [-1.,  0.]],

         [[ 2.,  0.],
          [ 0., -1.]]]], requires_grad=True)


In [4]:
print(mod)

tensor([[[[8., 8., 8.],
          [8., 4., 8.],
          [8., 8., 8.]],

         [[1., 2., 3.],
          [2., 1., 2.],
          [3., 2., 1.]]]], grad_fn=<MkldnnConvolutionBackward>)
